description: ""
intro: "The uMod database extensions implement a generalized database abstraction layer for both MySQL and SQLite."

topics:
  - title: "Open MySQL connection"
    summary: "Create a new connection to a MySql database by providing an address (URI & port), a database name, and authentication credentials."
  - title: "Close MySql connection"
    summary: "Close an existing connection to a MySql database."
  - title: "Query MySql database"
    summary: "Retrieve data from a MySql database, typically using a SELECT statement."
  - title: "Insert query"
    summary: "Insert records into a MySql database using an INSERT statement."
  - title: "Update query"
    summary: "Update existing records in a MySql database using an UPDATE statement."
  - title: "Delete query"
    summary: "Delete existing records from a MySql database using a DELETE statement."
  - title: "Non-query"
    summary: "By definition a non-query is a query which modifies data and does not retrieve data.  Insert, Update, and Delete queries are all considered non-queries."
