description: ""
intro: "The uMod database extensions implement a generalized database abstraction layer for both MySQL and SQLite."

topics:
  - title: "Open MySQL connection"
    summary: ""
  - title: "Close MySql connection"
    summary: ""
  - title: "Query MySql database"
    summary: ""
  - title: "Insert query"
    summary: ""
  - title: "Update query"
    summary: ""
  - title: "Delete query"
    summary: ""
  - title: "Non-query"
    summary: ""
