language: ruby
cache: bundler
install: bundle install
script: bundle exec jekyll build

git:
  depth: 1

branches:
  only: master

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: _site
  fqdn: umod.org
  name: uMod Bot
  email: deploy@umod.org
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master

notifications:
  email: false
