# Site
title: uMod
description: "Universal modding platform and plugin API for Unity, .NET/C#, and soon C++ games"
url: https://umod.org

# Community
home: https://umod.org
forums: https://forums.umod.org
twitter: https://twitter.com/theumod
patreon: https://www.patreon.com/umod

# Building
markdown: redcarpet
redcarpet:
  extensions: ["autolink", "filter_html", "hard_wrap", "no_images", "prettify", "strikethrough", "tables", "with_toc_data", "xhtml"]
permalink: /:title/
excerpt_separator: <!--more-->
collections:
  includes:
    output: true

# GitHub
github: https://github.com/theumod
plugins_org: umods
exclude: ["js/dev", "js/preprod", "plugins", "vendor", .gitignore", "*.sh", "*.ps1", "Gemfile*", "README.md", "gulpfile.js", "netlify.toml"]
