# Site
title: uMod
description: "Universal modding platform and plugin API for Unity, .NET/C#, and soon C++ games"
url: https://umod.org

# Community
forums: https://forums.umod.org
twitter: https://twitter.com/theumod
patreon: https://www.patreon.com/oxidemod

# Building
markdown: kramdown
kramdown:
  auto_ids: true
  input: GFM
permalink: /:title/
excerpt_separator: <!--more-->

# GitHub
repository: theumod/umod.org
plugins_org: umods
client_id: 644edf81174f14822070
exclude: ["js/dev", "js/preprod", "plugins", "vendor", .gitignore", "_test.sh", "Gemfile*", "README.md"]
