# Site
title: uMod
description: "Universal modding platform and plugin API for Unity, .NET/C#, and soon C++ games"
url: https://umod.org
google_analytics_id:
google_site_verification:

# Community
forums: https://forums.umod.org
twitter: https://twitter.com/theumod
discord:

# Building
markdown: kramdown
kramdown:
  input: GFM
permalink: /:title/
excerpt_separator: <!--more-->

# GitHub
repository: theumod/umod.org
plugins_org: umods
client_id: 644edf81174f14822070
exclude: ["js/dev", "js/preprod", "plugins", "vendor", .gitignore", "_test.sh", "Gemfile*", "README.md"]

# Jekyll
plugins:
  - github-pages
  - jekyll-avatar
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - kramdown
